# version: '3.7'

services:
  vercel-python-demo:
    container_name: vercel-python-demo
    build: .
    volumes:
      - .:/code
      - root_hist:/root/history # i keep roots history across everything
      - vscode-server:/root/.vscode-server
      - huggingface-cache:/root/.cache/huggingface
    stdin_open: true
    tty: true
    ports:
      - "8000:8000" # serving site
    # environment:
    #   STREAMLIT_SERVER_ADDRESS: 0.0.0.0
    #   STREAMLIT_SERVER_PORT: 8000
    #   # GOOGLE_CLOUD_PROJECT: 
    #   # GOOGLE_APPLICATION_CREDENTIALS: '/.config/gcloud/.json'
    working_dir: /code/my-app/api
    entrypoint:
      - uvicorn
      - index:app
      - --host=0.0.0.0
      - --reload 

volumes:
  root_hist:
    name: root_hist
    external: true
  vscode-server:
    name: vscode-server
    external: true
  huggingface-cache:
    name: huggingface-cache
    external: true